// Auto-generated by generate_system.py.
// Creates the real-estate finance workbook structure, formulas, and dropdowns.

const FINANCE_SYSTEM_TABS = {
  "Income": [
    [
      "תאריך",
      "צד נגדי",
      "פרויקט",
      "קטגוריה",
      "סכום",
      "מע\"מ",
      "אמצעי תשלום",
      "סטטוס",
      "הערות",
      "סכום כולל",
      "מזהה תנועה",
      "כפילות?",
      "שגיאה?"
    ]
  ],
  "Expenses": [
    [
      "תאריך",
      "צד נגדי",
      "פרויקט",
      "קטגוריה",
      "סכום",
      "מע\"מ",
      "אמצעי תשלום",
      "סטטוס",
      "הערות",
      "סכום כולל",
      "מזהה תנועה",
      "כפילות?",
      "שגיאה?"
    ]
  ],
  "Lists": [
    [
      "Payment_Methods",
      "Status",
      "Income_Categories",
      "Expense_Categories",
      "Projects"
    ],
    [
      "העברה בנקאית",
      "שולם",
      "מכירת נכס",
      "שיווק",
      "Project A"
    ],
    [
      "אשראי",
      "ממתין",
      "שכירות",
      "תחזוקה",
      "Project B"
    ],
    [
      "צ׳ק",
      "חלקי",
      "דמי תיווך",
      "משפטי",
      "Project C"
    ],
    [
      "מזומן",
      "בוטל",
      "ניהול נכס",
      "הנה\"ח",
      "Project D"
    ],
    [
      "ביט",
      "",
      "אחר",
      "עמלות סליקה",
      ""
    ],
    [
      "אחר",
      "",
      "",
      "אחר",
      ""
    ]
  ],
  "Category_Map": [
    [
      "keyword",
      "normalized_category",
      "type",
      "notes"
    ],
    [
      "פייסבוק",
      "שיווק",
      "הוצאה",
      "סיווג הוצאות פרסום"
    ],
    [
      "עו\"ד",
      "משפטי",
      "הוצאה",
      "סיווג הוצאות משפטיות"
    ],
    [
      "דמי ניהול",
      "ניהול נכס",
      "הכנסה",
      "זיהוי הכנסות מניהול"
    ]
  ],
  "RAW_Transactions": [
    [
      "created_at",
      "source",
      "external_id",
      "txn_date",
      "counterparty",
      "description",
      "amount",
      "vat",
      "currency",
      "payment_method",
      "project_raw",
      "category_raw",
      "direction_raw",
      "status_raw",
      "normalized_type",
      "normalized_category",
      "normalized_project",
      "status_normalized",
      "duplicate_flag",
      "error_flag",
      "unique_key"
    ]
  ],
  "Transactions_All": [
    [
      "תאריך",
      "סוג תנועה",
      "צד נגדי",
      "פרויקט",
      "קטגוריה",
      "סכום",
      "מע\"מ",
      "סכום כולל",
      "אמצעי תשלום",
      "סטטוס",
      "הערות",
      "מזהה תנועה"
    ]
  ],
  "Project_Profitability": [
    [
      "פרויקט",
      "הכנסות",
      "הוצאות",
      "רווח נקי",
      "שיעור רווחיות"
    ]
  ],
  "Tasks_Manager": [
    [
      "task_id",
      "created_at",
      "task_type",
      "priority",
      "related_project",
      "related_counterparty",
      "related_transaction_id",
      "task_title",
      "task_description",
      "owner",
      "due_date",
      "status",
      "sla_days",
      "aging_days",
      "is_overdue",
      "resolution_note",
      "resolved_at"
    ]
  ],
  "Dashboard": [
    [
      "metric",
      "value",
      "notes"
    ],
    [
      "הכנסות החודש",
      "",
      "מחושב מ-Transactions_All"
    ],
    [
      "הוצאות החודש",
      "",
      "מחושב מ-Transactions_All"
    ],
    [
      "רווח נקי",
      "",
      "הכנסות פחות הוצאות"
    ],
    [
      "תשלומים ממתינים",
      "",
      "סטטוס ממתין"
    ],
    [
      "כפילויות פתוחות",
      "",
      "Income + Expenses + RAW"
    ],
    [
      "שגיאות נתונים",
      "",
      "Income + Expenses + RAW"
    ]
  ]
};
const FINANCE_SYSTEM_FORMULAS = {
  "Income": [
    [
      "J2",
      "=IF(OR(E2=\"\",F2=\"\"),\"\",E2+F2)"
    ],
    [
      "K2",
      "=IF(A2=\"\",\"\",TEXT(A2,\"yyyymmdd\")&\"_\"&C2&\"_\"&E2)"
    ],
    [
      "L2",
      "=IF(K2=\"\",\"\",IF(COUNTIF($K:$K,K2)>1,\"כפול\",\"\"))"
    ],
    [
      "M2",
      "=IF(A2=\"\",\"\",IF(OR(E2<=0,F2<0,D2=\"\",C2=\"\",H2=\"\"),\"שגיאת הזנה\",\"\"))"
    ]
  ],
  "Expenses": [
    [
      "J2",
      "=IF(OR(E2=\"\",F2=\"\"),\"\",E2+F2)"
    ],
    [
      "K2",
      "=IF(A2=\"\",\"\",TEXT(A2,\"yyyymmdd\")&\"_\"&C2&\"_\"&E2)"
    ],
    [
      "L2",
      "=IF(K2=\"\",\"\",IF(COUNTIF($K:$K,K2)>1,\"כפול\",\"\"))"
    ],
    [
      "M2",
      "=IF(A2=\"\",\"\",IF(OR(E2<=0,F2<0,D2=\"\",C2=\"\",H2=\"\"),\"שגיאת הזנה\",\"\"))"
    ]
  ],
  "RAW_Transactions": [
    [
      "O2",
      "=IF(M2=\"\",\"\",IF(OR(LOWER(M2)=\"income\",LOWER(M2)=\"credit\"),\"הכנסה\",\"הוצאה\"))"
    ],
    [
      "R2",
      "=IF(N2=\"\",\"ממתין\",IF(REGEXMATCH(LOWER(N2),\"paid|success|completed\"),\"שולם\",\"ממתין\"))"
    ],
    [
      "U2",
      "=IF(D2=\"\",\"\",TEXT(D2,\"yyyymmdd\")&\"_\"&E2&\"_\"&G2&\"_\"&C2)"
    ],
    [
      "S2",
      "=IF(U2=\"\",\"\",IF(COUNTIF($U:$U,U2)>1,\"כפול\",\"\"))"
    ],
    [
      "T2",
      "=IF(OR(D2=\"\",E2=\"\",G2=\"\",O2=\"\"),\"שגיאה\",\"\")"
    ]
  ],
  "Transactions_All": [
    [
      "A2",
      "={FILTER({Income!A2:A,\"הכנסה\",Income!B2:B,Income!C2:C,Income!D2:D,Income!E2:E,Income!F2:F,Income!J2:J,Income!G2:G,Income!H2:H,Income!I2:I,Income!K2:K},Income!A2:A<>\"\");FILTER({Expenses!A2:A,\"הוצאה\",Expenses!B2:B,Expenses!C2:C,Expenses!D2:D,Expenses!E2:E,Expenses!F2:F,Expenses!J2:J,Expenses!G2:G,Expenses!H2:H,Expenses!I2:I,Expenses!K2:K},Expenses!A2:A<>\"\")}"
    ]
  ],
  "Project_Profitability": [
    [
      "A2",
      "=UNIQUE(FILTER(Transactions_All!D2:D,Transactions_All!D2:D<>\"\"))"
    ],
    [
      "B2",
      "=SUMIFS(Transactions_All!H:H,Transactions_All!D:D,A2,Transactions_All!B:B,\"הכנסה\")"
    ],
    [
      "C2",
      "=SUMIFS(Transactions_All!H:H,Transactions_All!D:D,A2,Transactions_All!B:B,\"הוצאה\")"
    ],
    [
      "D2",
      "=B2-C2"
    ],
    [
      "E2",
      "=IF(B2=0,\"\",D2/B2)"
    ]
  ],
  "Tasks_Manager": [
    [
      "A2",
      "=\"TSK-\"&TEXT(ROW(A2)-1,\"00000\")"
    ],
    [
      "N2",
      "=IF(B2=\"\",\"\",TODAY()-B2)"
    ],
    [
      "O2",
      "=IF(OR(K2=\"\",L2=\"הושלם\"),\"\",IF(TODAY()>K2,\"באיחור\",\"בזמן\"))"
    ]
  ],
  "Dashboard": [
    [
      "B2",
      "=SUMIFS(Transactions_All!H:H,Transactions_All!B:B,\"הכנסה\",Transactions_All!A:A,\">=\"&EOMONTH(TODAY(),-1)+1,Transactions_All!A:A,\"<=\"&EOMONTH(TODAY(),0))"
    ],
    [
      "B3",
      "=SUMIFS(Transactions_All!H:H,Transactions_All!B:B,\"הוצאה\",Transactions_All!A:A,\">=\"&EOMONTH(TODAY(),-1)+1,Transactions_All!A:A,\"<=\"&EOMONTH(TODAY(),0))"
    ],
    [
      "B4",
      "=B2-B3"
    ],
    [
      "B5",
      "=SUMIFS(Transactions_All!H:H,Transactions_All!J:J,\"ממתין\")"
    ],
    [
      "B6",
      "=COUNTIF(Income!L:L,\"כפול\")+COUNTIF(Expenses!L:L,\"כפול\")+COUNTIF(RAW_Transactions!S:S,\"כפול\")"
    ],
    [
      "B7",
      "=COUNTIF(Income!M:M,\"שגיאת הזנה\")+COUNTIF(Expenses!M:M,\"שגיאת הזנה\")+COUNTIF(RAW_Transactions!T:T,\"שגיאה\")"
    ]
  ]
};

function setupRealEstateFinanceSystem() {
  const spreadsheet = SpreadsheetApp.getActiveSpreadsheet();

  Object.keys(FINANCE_SYSTEM_TABS).forEach(function(sheetName) {
    const values = FINANCE_SYSTEM_TABS[sheetName];
    let sheet = spreadsheet.getSheetByName(sheetName);
    if (!sheet) {
      sheet = spreadsheet.insertSheet(sheetName);
    }
    sheet.clear();
    sheet.getRange(1, 1, values.length, values[0].length).setValues(values);
    sheet.setFrozenRows(1);
    sheet.autoResizeColumns(1, values[0].length);
  });

  Object.keys(FINANCE_SYSTEM_FORMULAS).forEach(function(sheetName) {
    const sheet = spreadsheet.getSheetByName(sheetName);
    if (!sheet) return;
    FINANCE_SYSTEM_FORMULAS[sheetName].forEach(function(item) {
      sheet.getRange(item[0]).setFormula(item[1]);
    });
  });

  applyFinanceDataValidation_(spreadsheet);
  SpreadsheetApp.flush();
}

function applyFinanceDataValidation_(spreadsheet) {
  const lists = spreadsheet.getSheetByName('Lists');
  if (!lists) return;

  const paymentRule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(lists.getRange('A2:A100'), true)
    .setAllowInvalid(false)
    .build();
  const statusRule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(lists.getRange('B2:B100'), true)
    .setAllowInvalid(false)
    .build();
  const incomeCategoryRule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(lists.getRange('C2:C100'), true)
    .setAllowInvalid(false)
    .build();
  const expenseCategoryRule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(lists.getRange('D2:D100'), true)
    .setAllowInvalid(false)
    .build();
  const projectRule = SpreadsheetApp.newDataValidation()
    .requireValueInRange(lists.getRange('E2:E100'), true)
    .setAllowInvalid(false)
    .build();

  const income = spreadsheet.getSheetByName('Income');
  const expenses = spreadsheet.getSheetByName('Expenses');
  if (income) {
    income.getRange('C2:C1000').setDataValidation(projectRule);
    income.getRange('D2:D1000').setDataValidation(incomeCategoryRule);
    income.getRange('G2:G1000').setDataValidation(paymentRule);
    income.getRange('H2:H1000').setDataValidation(statusRule);
  }
  if (expenses) {
    expenses.getRange('C2:C1000').setDataValidation(projectRule);
    expenses.getRange('D2:D1000').setDataValidation(expenseCategoryRule);
    expenses.getRange('G2:G1000').setDataValidation(paymentRule);
    expenses.getRange('H2:H1000').setDataValidation(statusRule);
  }
}
